# Test build the MoveIt! tutorials. Author: Dave Coleman
sudo: required
dist: trusty
services:
  - docker
language: ruby
rvm:
  - 2.4
python:
  - "2.7"
cache: ccache
compiler: gcc

# Define some config vars
env:
  global:
    - MOVEIT_CI_TRAVIS_TIMEOUT=85  # Travis grants us 90 min, but we add a safety margin of 5 min
    - ROS_REPO=ros
    - ROS_DISTRO=melodic
    - UPSTREAM_WORKSPACE=moveit_tutorials.rosinstall
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - CXXFLAGS="-Wall -Wextra -Wwrite-strings -Wunreachable-code -Wpointer-arith -Wredundant-decls -Wno-unused-parameter -Wno-unused-but-set-parameter -Wno-unused-function"
    - WARNINGS_OK=false
    - REPOSITORY_NAME=${PWD##*/}

# before_install: # Use this to prepare the system to install prerequisites or dependencies
  # - ./travis.sh
before_script:
  - git clone -q --depth=1 https://github.com/ros-planning/moveit_ci.git .moveit_ci

script:
  # Build tutorial examples
  - .moveit_ci/travis.sh
  # Install htmlpoofer
  - gem update --system -q
  - gem --version
  - gem install html-proofer -q
  # Test build with non-ROS wrapped Sphinx command to allow warnings and errors to be caught
  - sphinx-build -W -b html . native_build
  # Test build with ROS-version of Sphinx command so that it is generated same as ros.org
  - rosdoc_lite -o build .
  # Run HTML tests on generated build output to check for 404 errors, etc
  - htmlproofer ./build --only-4xx --check-html --file-ignore ./build/html/genindex.html,./build/html/search.html,./build/html/index-msg.html --alt-ignore '/.*/' --url-ignore '#'

# after_success and deploy are skipped if build is broken
after_success:
  # Tell GitHub Pages not to bypass Jekyll processing
  - touch build/html/.nojekyll

deploy:
  # Deploy to gh-pages branch
  provider: pages
  # Don't delete built files
  skip-cleanup: true
  # Add to Environment Variables section of Travis CI repository settings page
  github-token: $GITHUB_TOKEN
  # Only copy build output directory to gh-pages
  local_dir: build/html
  on:
    # Source branch
    branch: master
